server:
  port: 8081

spring:
  application:
    name: mcsv-cines

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://40.233.27.238:3307/cinema_db
    username: app_user
    password: appSa456.
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect

  kafka:
    admin:
      auto-create: true
    bootstrap-servers:
#      - localhost:9092
      - b-1.kafkap2sa.uqqw98.c10.kafka.us-east-1.amazonaws.com:9094
      - b-2.kafkap2sa.uqqw98.c10.kafka.us-east-1.amazonaws.com:9094
    consumer:
      group-id: cines-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        security.protocol: SSL
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        security.protocol: SSL



eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8765/
    register-with-eureka: true
    fetch-registry: true

app:
  frontend:
    base-url: https://tu-frontend.com
  security:
    dev-return-token: true
  kafka:
    enabled: true
    topic:
      cines: cines.events.v1
      verificar-cine: verificar-cine
      propiedad-anuncio-creado: propiedad-anuncio-creado
      propiedad-facturacion-generada: propiedad-facturacion-generada
      credito-cine: credito-cine
      debito-cine: debito-cine
      generar-bloqueo-anuncio: generar-bloqueo-anuncio